[package]
name = "wave-function"
version = "0.1.0"
authors = ["Muresan73 <grge73@outlook.com>"]
license = "MIT"
edition = "2021"

[dependencies]
env_logger = "0.10.1"
log = "0.4.20"
ndarray = { version = "0.15.6", features = ["rayon"] }
rayon = "1.8.0"
