[package]
name = "wave-function"
version = "0.1.0"
authors = ["Muresan73 <grge73@outlook.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.26.1"
ndarray = { version = "0.15.6", features = ["rayon"] }
rayon = "1.8.0"
tui = { package = "ratatui", version = "0.21.0" }
